# Generated by Django 2.0.1 on 2018-01-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('place', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, verbose_name='электронная почта')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='пол')),
                ('birth_date', models.DateTimeField(auto_now_add=True, verbose_name='дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('mark', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightseens.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightseens.User')),
            ],
        ),
    ]
